mktdata:
  source: "kaiko"
  # path: "/run/user/1000/gvfs/sftp:host=89.36.67.26,port=2806/Sety/mktdata/vol_surfaces/drbt"
  path: "/home/user/DynamicHedgeBacktest/data/kaiko"
  # path: "/home/user/DynamicHedgeBacktest/data/kaiko_test"
  funding_rate: 0
  slippage:
    delta: 0.001  # relative
    vega: 0.01  # absolute
    rho: 0  # absolute
strategy:
  type: "ShortGamma"
  currency: "btc" # lowercase
  equity: 1000000
  theta_hedge:
    gamma_tenor: 7  # in days
    target: [0.5, 1.5]  # in yield per annum, will determine theta
    theta_hurdle: 0.5  # vs benchmark
  delta_hedging:
    target: [-0.0025, 0.0025] # for yield = 100% and vol = 60%, delta = 0.018 gives same var as theta pnl
backtest:
  backtest_window: 30  # in days
  volfactor: 1.0
  test: false