mktdata:
  source: "kaiko"
strategy:
  type: "ShortGamma"
  currency: "BTC"
  notional_coin: 1.0
  gamma_tenor: 7  # in days
  theta_target: 0.01
  delta_hedging:
    target: 0
    threshold: 0.01
backtest:
  backtest_window: 90  # in days
  volfactor: 1.0