mktdata:
  source: "kaiko"
  slippage:
    delta: 0.001  # relative
    vega: 0.02  # absolute
    rho: 0  # absolute
strategy:
  type: "ShortGamma"
  currency: "BTC"
  equity: 1000000
  gamma_tenor: 30  # in days
  yield_target: 0.5  # will determine theta
  delta_hedging:
    target: 0
    threshold: 0.01
backtest:
  backtest_window: 90  # in days
  volfactor: 1.0